apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-data-disk
  namespace: clase8
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
