apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: clase8
  namespace: clase8
spec:
  ports:
    - port: 80
  selector:
    app: clase8
    tier: frontend
  type: LoadBalancer
