apiVersion: v1
kind: Pod
metadata:
  name:  clase6
  namespace: clase6
  labels:
    app:  clase6
spec:
  containers:
  - name: hola-aws101
    image: dolguin/hola-aws101:latest
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 100Mi
    ports:
    - containerPort: 80
    volumeMounts:
      - name: test-volume
        mountPath: /mnt/volumen/
        readOnly: true
  volumes:
    - name: test-volume
      # This AWS EBS volume must already exist.
      awsElasticBlockStore:
        volumeID: "vol-0bb8ed1bd83014f5f"
        fsType: ext4
