apiVersion: v1
kind: ConfigMap
metadata:
  name: aws101-config
  namespace: clase5
  labels:
    app:  clase5
data:
  # Clave-Valor; cada Clave (key) esta asignada a un valor (value) simple
  NGINX_PORT: "80"
  DATABASE_HOST: "db.aws101.org"
  # Archivos como Clave(key)
  default.conf: |
    server {
      listen  80;
      listen  [::]:80;
      server_name  localhost;

      location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
      }

      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }

      add_header Cache-Control "no-cache, no-store";

    }
