apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: clase11
  namespace: clase11
spec:
  ports:
    - port: 80
  selector:
    app: clase11
    tier: frontend
  clusterIP: None
